
version: '3'

services:
  chatbot:
    build: .
    container_name: chatbot-iaturbo
    restart: unless-stopped
    ports:
      - "8089:80"
    networks:
      - default
      - iaturbo-network
    volumes:
      - ./dify/completed:/var/www/html/dify/completed
      - ./dify/pending:/var/www/html/dify/pending
      - ./dify/logs:/var/www/html/dify/logs
      - ./speech/output:/var/www/html/speech/output
      - ./speech/input:/var/www/html/speech/input
      - ./speech/logs:/var/www/html/speech/logs
      - ./logs:/var/www/html/logs
      - ./config.php:/var/www/html/config.php:ro
    environment:
      # URLs e caminhos base
      - BASE_URL=http://172.16.20.237:8089
      - BASE_URL_INTERNAL=http://172.16.20.237:8089

      # Configurações do Dify
      - DIFY_API_URL=http://172.16.20.237:8080/v1
      - DIFY_API_KEY=app-uwl036ZPjVe9Gwkdv7H7X9yW

      # Chaves de API e credenciais
      - OPENAI_API_KEY=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
      - TRELLO_API_KEY=eede912d114a15aacb161506dd170cf5
      - TRELLO_API_TOKEN=ATTA3176dbbbc3c0e5a22bdb3fcba706ac35c9b4b96e930098e562d153b0a5758d6718848C8E
      - TRELLO_BOARD_ID=669eaa63f0fde49eefa7381a
      - TRELLO_LIST_ID=669eaa743dce7b9bf018a635
      - SLACK_WEBHOOK_URL=https://hooks.slack.com/services/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

      # Configurações do serviço de fala
      - SPEECH_MODEL=tts-1
      - SPEECH_VOICE=shimmer

      # Configurações de diretórios
      - OUTPUT_DIR=/var/www/html/speech/output/
      - LOGS_DIR=/var/www/html/logs/
      - PENDING_DIR=/var/www/html/dify/pending/
      - COMPLETED_DIR=/var/www/html/dify/completed/

      # Flags para habilitar/desabilitar funcionalidades
      - ENABLE_TRELLO=true
      - ENABLE_SLACK=true
      - ENABLE_AUDIO=true

      # Configurações de estilo
      - CSS_THEME=default.css
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/public/health.php"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

networks:
  default:
  iaturbo-network:
    external: true
