openapi: 3.0.0
info:
  title: API de Orçamento de Chatbots IA Turbo
  version: 1.1.0
  description: >
    API para gerar orçamentos detalhados de chatbots personalizados com base em módulos como Conversa Com IA, Conectado, e Multimídia.
    Suporta seleção de níveis de personalização, integração com APIs, e suporte contínuo.
servers:
  - url: https://iaturbo.com.br/wp-content/uploads/scripts/precos/obterOrcamento.php
paths:
  /obterOrcamento.php:
    post:
      summary: Gera um orçamento baseado nos parâmetros fornecidos.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - nome
                - email
                - whatsapp
                - ConversaComIA_DescricaoLead
                - ConversaComIA_NivelPersonalizacaoConversa
              properties:
                nome:
                  type: string
                  description: Nome do cliente.
                email:
                  type: string
                  description: Email do cliente.
                whatsapp:
                  type: string
                  description: Número de WhatsApp do cliente, em formato internacional (+5511912345678).
                ConversaComIA_DescricaoLead:
                  type: string
                  description: Objetivo principal do chatbot, como vendas, suporte, etc.
                ConversaComIA_NivelPersonalizacaoConversa:
                  type: string
                  enum: [Basico, Padrao, Avancado]
                  description: Nível de personalização da conversa conforme a complexidade do chatbot.
                ConversaComIA_SuporteMelhoriaContinua:
                  type: string
                  enum: [Basico, Padrao, Avancado]
                  description: Nível de suporte e melhoria contínua para o módulo Conversa Com IA.
                Conectado_RedesSociais_WhatsApp:
                  type: string
                  enum: [true]
                  description: Integração com WhatsApp para interação direta.
                Conectado_RedesSociais_Facebook:
                  type: string
                  enum: [true]
                  description: Integração com Facebook, incluindo respostas automáticas no Messenger.
                Conectado_RedesSociais_Instagram:
                  type: string
                  enum: [true]
                  description: Integração com Instagram, incluindo DMs e comentários.
                Conectado_RedesSociais_Telegram:
                  type: string
                  enum: [true]
                  description: Integração com Telegram para interação em grupos e canais.
                Conectado_APIPublica:
                  type: array
                  items:
                    type: object
                    properties:
                      Descricao:
                        type: string
                        description: Descrição da Conexão com APIs Públicas integrada.
                      Nivel:
                        type: string
                        enum: [Basico, Padrao, Avancado]
                        description: Complexidade da integração com a Conexão com APIs Públicas.
                Conectado_APISobMedida_Descricao:
                  type: string
                  description: Descrição da integração personalizada para APIs específicas do cliente.
                Conectado_SuporteMelhoriaContinua:
                  type: string
                  enum: [Basico, Padrao, Avancado]
                  description: Nível de suporte e melhoria contínua para o módulo Conectado.
                Multimidia_Voz_AudicaoAtiva:
                  type: string
                  enum: [true]
                  description: Habilitar conversão de voz para texto.
                Multimidia_Voz_AudicaoAtiva_DescricaoLead:
                  type: string
                  description: Descrição personalizada para a funcionalidade de voz para texto.
                Multimidia_Voz_VozPersonalizada:
                  type: string
                  enum: [true]
                  description: Habilitar conversão de texto para voz.
                Multimidia_Voz_VozPersonalizada_DescricaoLead:
                  type: string
                  description: Descrição personalizada para a funcionalidade de texto para voz.
                Multimidia_Imagem_VisaoInteligente:
                  type: string
                  enum: [true]
                  description: Permitir interpretação de documentos e imagens.
                Multimidia_Imagem_CriadorVisual:
                  type: string
                  enum: [true]
                  description: Habilitar criação de imagens a partir de descrições textuais.
                Multimidia_SuporteMelhoriaContinua:
                  type: string
                  enum: [Basico, Padrao, Avancado]
                  description: Nível de suporte e melhoria contínua para o módulo Multimídia.
      responses:
        '200':
          description: Orçamento gerado com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  LeadInfo:
                    type: object
                    description: Informações pessoais do cliente.
                  ParametrosEntrada:
                    type: object
                    description: Parâmetros fornecidos para o orçamento.
                  ItensConfigurados:
                    type: array
                    items:
                      type: object
                      properties:
                        Item:
                          type: string
                          description: Nome do módulo configurado.
                        Nome:
                          type: string
                          description: Nome detalhado do item configurado.
                        DescricaoPrincipal:
                          type: string
                          description: Descrição principal do item.
                        DescricaoPersonalizada:
                          type: string
                          description: Detalhamento da personalização.
                        Custo:
                          type: number
                          description: Custo total.
                        Tempo:
                          type: number
                          description: Tempo de implementação.
                  ResumoGeral:
                    type: object
                    description: Resumo dos custos e prazos.
