openapi: 3.0.0
info:
  title: API de Orçamento de Chatbots IA Turbo
  version: 1.0.0
  description: API para gerar orçamentos de chatbots personalizados com base nas especificações fornecidas.
servers:
  - url: https://iaturbo.com.br/wp-content/uploads/scripts/precos/obterOrcamento.php
paths:
  /obterOrcamento.php:
    post:
      summary: Gera um orçamento baseado nos parâmetros fornecidos.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - nome
                - email
                - whatsapp
                - ConversaComIA_DescricaoLead
                - ConversaComIA_NivelPersonalizacaoConversa
                - ConversaComIA_SuporteMelhoriaContinua
              properties:
                ConversaComIA_DescricaoLead:
                  type: string
                  description: Descrição personalizada do chatbot de conversa com IA.
                ConversaComIA_NivelPersonalizacaoConversa:
                  type: string
                  enum: [Basico, Padrao, Avancado]
                  description: Nível de customização do prompt do chatbot.
                ConversaComIA_SuporteMelhoriaContinua:
                  type: string
                  enum: [Basico, Padrao, Avancado]
                  description: Nível de suporte e monitoramento contínuo para o chatbot de conversa com IA.
                Conectado_RedesSociais_WhatsApp:
                  type: string
                  enum: [true]
                  description: Integração com WhatsApp.
                Conectado_RedesSociais_Facebook:
                  type: string
                  enum: [true]
                  description: Integração com Facebook.
                Conectado_RedesSociais_Instagram:
                  type: string
                  enum: [true]
                  description: Integração com Instagram.
                Conectado_RedesSociais_Telegram:
                  type: string
                  enum: [true]
                  description: Integração com Telegram.
                Conectado_APIPublica:
                  type: array
                  items:
                    type: object
                    properties:
                      Descricao:
                        type: string
                        description: Descrição da integração com a API pública.
                      Nivel:
                        type: string
                        enum: [Basico, Padrao, Avancado]
                        description: Nível de complexidade da integração.
                Conectado_ConexaoPersonalizada_Descricao:
                  type: string
                  description: Descrição da integração com Conexão Personalizada.
                Conectado_SuporteMelhoriaContinua:
                  type: string
                  enum: [Basico, Padrao, Avancado]
                  description: Nível de suporte e monitoramento contínuo para integrações.
                Multimidia_Audio_VozParaTexto:
                  type: string
                  enum: [true]
                  description: Ativar funcionalidade de voz para texto.
                Multimidia_Audio_VozParaTexto_DescricaoLead:
                  type: string
                  description: Descrição personalizada da funcionalidade de voz para texto.
                Multimidia_Audio_TextoParaVoz:
                  type: string
                  enum: [true]
                  description: Ativar funcionalidade de texto para voz.
                Multimidia_Audio_TextoParaVoz_DescricaoLead:
                  type: string
                  description: Descrição personalizada da funcionalidade de texto para voz.
                Multimidia_Imagem_ImagemParaTexto:
                  type: string
                  enum: [true]
                  description: Ativar funcionalidade de imagem para texto.
                Multimidia_Imagem_ImagemParaTexto_DescricaoLead:
                  type: string
                  description: Descrição personalizada da funcionalidade de imagem para texto.
                Multimidia_Imagem_TextoParaImagem:
                  type: string
                  enum: [true]
                  description: Ativar funcionalidade de texto para imagem.
                Multimidia_Imagem_TextoParaImagem_DescricaoLead:
                  type: string
                  description: Descrição personalizada da funcionalidade de texto para imagem.
                Multimidia_SuporteMelhoriaContinua:
                  type: string
                  enum: [Basico, Padrao, Avancado]
                  description: Nível de suporte e monitoramento contínuo para funcionalidades multimídia.
                nome:
                  type: string
                  description: Nome do cliente.
                email:
                  type: string
                  description: Email do cliente.
                whatsapp:
                  type: string
                  description: Número de WhatsApp do cliente. No formato internacional E.164 (mínimo de 10 e máximo de 15 dígitos, iniciando com '+')
      responses:
        '200':
          description: Orçamento gerado com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  ParametrosEntrada:
                    type: object
                    description: Parâmetros recebidos pela API.
                  ItensConfigurados:
                    type: array
                    description: Lista de itens configurados com seus detalhes.
                    items:
                      type: object
                      properties:
                        Item:
                          type: string
                          description: Identificação do item.
                        DescricaoPrincipal:
                          type: string
                        DescricaoPersonalizada:
                          type: string
                        Nivel:
                          type: string
                        DescricaoCustomizacao:
                          type: string
                        Custo:
                          type: number
                        Tempo:
                          type: number
                        Categoria:
                          type: string
                        Aviso:
                          type: string
                  ResumoGeral:
                    type: object
                    properties:
                      CustoImplementacao:
                        type: number
                      TempoImplementacao:
                        type: number
                      CustoManutencao:
                        type: number
                      Subtotais:
                        type: object
                      TextoResumo:
                        type: string
        '400':
          description: Erro nos parâmetros enviados.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Mensagem de erro detalhada.